services:
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONTAINER_USER: ${CONTAINER_USER:-user}
        CONTAINER_GROUP: ${CONTAINER_GROUP:-group}
        XDEBUG_DIR: ${XDEBUG_DIR}
    environment:
      - DISPLAY=${DISPLAY}
    image: php-native:1.0
    volumes:
      - ${PROJECT_DIR}:/var/www/html
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /var/www/html
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ${NGINX_DIR}:/etc/nginx/conf.d/default.conf
      - ${PROJECT_DIR}/:/var/www/html:ro
    depends_on:
      - php
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  mysql-data: